base: "BTC"

# the default is the first currency
quotes:
  - { code: "USD", symbol: "$", name: "US Dollar", flag: "🇺🇸" }
  - { code: "JMD", symbol: "J$", name: "Jamaican Dollar", flag: "🇯🇲" }
  # - { code: "EUR", symbol: "€", name: "Euro", flag: "🇪🇺" }
  # - { code: "GBP", symbol: "£", name: "British Pound", flag: "🇬🇧" }
  # - { code: "XCD", symbol: "$", name: "East Caribbean Dollar", flag: "🇦🇬" }
  # - { code: "ANG", symbol: "ƒ", name: "Netherlands Antillean Guilder", flag: "🇨🇼" }
  # - { code: "HTG", symbol: "G", name: "Haitian Gourde", flag: "🇭🇹" }
  # - { code: "BSD", symbol: "$", name: "Bahamian Dollar", flag: "🇧🇸" }
  # - { code: "BBD", symbol: "$", name: "Barbadian Dollar", flag: "🇧🇧" }
  # - { code: "BZD", symbol: "BZ$", name: "Belize Dollar", flag: "🇧🇿" }
  # - { code: "KYD", symbol: "$", name: "Cayman Islands Dollar", flag: "🇰🇾" }
  # - { code: "CUP", symbol: "$", name: "Cuban Peso", flag: "🇨🇺" }
  # - { code: "DOP", symbol: "RD$", name: "Dominican Peso", flag: "🇩🇴" }
  # - { code: "TTD", symbol: "TT$", name: "Trinidad and Tobago Dollar", flag: "🇹🇹" }
exchanges:
- name: "Ibex"
  enabled: true
  quoteAlias: "*"
  base: "BTC"
  quote: "USD"
  provider: "ibex"
  cron: "*/15 * * * * *"
  config:
    cacheSeconds: 180
- name: "free-currency-rates-usd"
  enabled: true
  quoteAlias: "*"
  base: "BTC"
  quote: "*"
  excludedQuotes: ["USD"]
  provider: "free-currency-rates"
  cron: "*/5 * * * * *"
  config:
    baseUrl: "https://cdn.jsdelivr.net/npm/@fawazahmed0/currency-api@latest/v1/currencies"
    fallbackUrl: "https://currency-api.pages.dev/v1/currencies"
    cacheSeconds: 1800
- name: "kraken"
  enabled: true
  quoteAlias: "*"
  base: "BTC"
  quote: "*"
  excludedQuotes: ["USD"]
  provider: "ccxt"
  cron: "*/20 * * * * *"
- name: "bitstamp"
  enabled: true
  quoteAlias: "*"
  base: "BTC"
  quote: "*"
  excludedQuotes: ["USD"]
  provider: "ccxt"
  cron: "*/15 * * * * *"

# exchanges:
  # - name: "bitfinex2"
    # enabled: true
    # quoteAlias: "USD"
    # base: "BTC"
    # quote: "USD"
    # provider: "ccxt"
    # cron: "*/15 * * * * *"
#   - name: "exchangeratehost"
#     enabled: false
#     quoteAlias: "*"
#     base: "USD"
#     quote: "*"
#     excludedQuotes: []
#     provider: "exchangeratehost"
#     cron: "*/5 * * * * *"
#     config:
#       baseUrl: "https://api.exchangerate.host"
#       apiKey: "<your api key>"
#       cacheSeconds: 1800
#   - name: "currencybeacon"
#     enabled: false
#     quoteAlias: "*"
#     base: "USD"
#     quote: "*"
#     excludedQuotes: []
#     provider: "currencybeacon"
#     cron: "*/5 * * * * *"
#     config:
#       baseUrl: "https://api.currencybeacon.com/v1"
#       apiKey: "<your api key>"
#       cacheSeconds: 900
#   - name: "yadio-btc"
#     enabled: false
#     base: "BTC"
#     quote: ["ARS", "LBP"]
#     provider: "yadio"
#     cron: "*/5 * * * * *"
#     config:
#       baseUrl: "https://api.yadio.io/exrates"
#       cacheSeconds: 900
#   - name: "exchangeratesapi"
#     enabled: false
#     quoteAlias: "CRC"
#     base: "USD"
#     quote: "CRC"
#     provider: "exchangeratesapi"
#     cron: "*/5 * * * * *"
#     config:
#       baseUrl: "http://api.exchangeratesapi.io/v1"
#       apiKey: "<your api key>"
#       cacheSeconds: 14400
