name: "Realtime Check code"
on:
  push:
    branches: [main]
    paths:
      - "Makefile"
      - "*.json"
      - "yarn.lock"
      - "realtime/**"
  pull_request:
    branches: [main]
    paths:
      - "Makefile"
      - "*.json"
      - "yarn.lock"
      - "realtime/**"
jobs:
  check-code:
    name: Check Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
      - run: yarn install --frozen-lockfile
      - name: Run check code
        run: make realtime-check-code
